image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
  - port: 8000
    onOpen: notify
    visibility: public
  - port: 5432
    onOpen: ignore
    visibility: private
  - port: 6379
    onOpen: ignore
    visibility: private

tasks:
  - name: Start Docker Compose
    init: |
      echo "📦 Installing Python deps..."
      cd backend && poetry install

      echo "📦 Installing frontend deps..."
      cd ../frontend && pnpm install

      echo "🐳 Building containers..."
      docker-compose build
    command: |
      echo "🚀 Starting services..."
      docker-compose up -d
      echo "✅ All services started."
      bash

vscode:
  extensions:
    - ms-python.python
    - ms-azuretools.vscode-docker
    - msjsdiag.vscode-react-native
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint

github:
  prebuilds:
    addBadge: true
    runOnPush: true
    runOnPullRequest: true

# Optionally, add environment variables if needed
# env:
#   - name: GITPOD_WORKSPACE_URL
#     value: ${GITPOD_WORKSPACE_URL}
