image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Docker Services
    init: docker compose build
    command: docker compose up

ports:
  - port: 8000
    onOpen: open-preview
  - port: 3000
    onOpen: open-browser
